#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

NAME=squeezenfc
ZONE_NAME=`hostname`
MAC=`ifconfig -a |grep eth0 | awk '{print tolower($5)}'`
DAEMON=/usr/bin/$NAME
PIDLOCATION=/var/run/$NAME
PIDFILE=$PIDLOCATION/$NAME.pid
DAEMON_ARGS="$MAC"

[ -x $binary ] || exit 0

[ -d $PIDLOCATION ] || mkdir $PIDLOCATION

start() {
    echo "Starting squeezenfc"
    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON" -b --oknodo -- $DAEMON_ARGS
}

stop() {
    echo "Shutting down squeezenfc"
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" --retry 1 --oknodo
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        ;;
esac

exit 0
